name: Deploy nginx to EKS

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: prod-demo-cluster
  NAMESPACE: default

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy nginx to EKS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

    - name: Deploy nginx
      run: |
        kubectl apply -f - <<EOF
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-test
          namespace: $NAMESPACE
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: nginx-test
          template:
            metadata:
              labels:
                app: nginx-test
            spec:
              containers:
              - name: nginx
                image: nginx:latest
                ports:
                - containerPort: 80
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: nginx-test
          namespace: $NAMESPACE
        spec:
          selector:
            app: nginx-test
          ports:
            - protocol: TCP
              port: 80
              targetPort: 80
          type: LoadBalancer
        EOF

    - name: Wait for nginx rollout
      run: |
        kubectl rollout status deployment/nginx-test -n $NAMESPACE

    - name: Get service info
      run: |
        kubectl get svc nginx-test -n $NAMESPACE
        kubectl get pods -n $NAMESPACE -l app=nginx-test
